---
title: "Fitst git blog"
date: 2018-11-06
---

title: Fitst git blog
author: GitHub User 0pnty 
email: bob@aol.com
description: > # this means to ignore newlines until "baseurl:"
  blah blah blah Trump sucks. if you found this you are good aat osint.  

# social links
twitter_username: @0pnty
github_username:  0pnty

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
---
